% **************************************************************** 
% *** HOWTO
% **************************************************************** 
% 0) Do not modify this template file "set_parameters_for_data_generation_template.m"
% 1) Create a new copy of this file "set_parameters_for_data_generation_template.m" in your local environment and rename it into "set_parameters_for_data_generation.m"
% 2) Indicate all the variables according to your local environment and experiment
% 3) Use your own "set_parameters_for_data_generation.m" file to run the code
% 4) Do not commit/push your own "set_parameters_for_data_generation.m" file to the collective repository, it is not relevant for other people
% ****************************************************************
function [...
    output_root_folder,...
    path_to_rec_toolbox,...
    deviceId,...
    speed_of_sound_range,...
    image_folder,...
    splits,...
    voc2012_start_indices_per_split,...
    num_considered_voc2012_imgs_per_split,...
    number_of_different_gt_sos_for_each_img_per_split,...
    use_gt_sos_also_as_rec_sos,...
    number_of_different_rec_sos_for_each_img_per_split,...
    random_sinogram_scaling,...
    max_scale_factor_for_initial_images,...
    path_to_invivo_sinograms_for_std_distr_estimation,...
    initial_img_transform,...
    path_to_studies_folders_with_raw_data,...
    data_name_prefix,...
    path_to_csv,...
    func_name_pulse_suffix,...
    broken_transducers,...
    use_all_sos_instead_of_only_gt_sos_for_invivo_rec] = set_parameters_for_data_generation()

% General parameters for synthesized and invivo datasets
output_root_folder = '???';                     % Path to intended output folder for the generated data.
path_to_rec_toolbox = '???';                    % Path to model-based reconstruction toolbox.
deviceId = '???';                               % Id of a MOST device defined in the model-based reconstruction toolbox.
speed_of_sound_range = 1475 : 5 : 1525;         % Range of supported speed of sound values.

% Parameters for synthesizing a training and validation dataset
image_folder = '???';                                        % Path to 'JPEGImages' folder of VOC2012 dataset.
splits = {'train', 'val'};                                   % Cell array with the split names of the generated dataset.
voc2012_start_indices_per_split = [1, 12001];                % Incides of first VOC2012 image per split to ensure that no image is used more than one split.
num_considered_voc2012_imgs_per_split = [8000, 2000];        % Array with the number of VOC2012 iamges that are processed for each split.
number_of_different_gt_sos_for_each_img_per_split = [1, 1];  % Number of forward simulations per VOC2012 image with randomly drawn ground truth SoS values from the defined range.
use_gt_sos_also_as_rec_sos = true;                           % Reconstruct each sinogram with the SoS from the forward simulation or with randomly drawn SoS values from the defined range.
number_of_different_rec_sos_for_each_img_per_split = [1, 1]; % Number of randomly drawn SoS values per split, with which each synthesized sinogram is reconstructed. This parameter is ignored if use_gt_sos_also_as_rec_sos==true.
% Total number of samples per split: voc2012_start_indices_per_split(split) * number_of_different_gt_sos_for_each_img_per_split(split) * number_of_different_rec_sos_for_each_img_per_phase(split).
random_sinogram_scaling = 'UNIFORM_RANGE';                   % 'UNIFORM_RANGE' or 'MATCH_STD_DISTR_OF_INVIVO_SINOGRAMS'; see explanation of the next two parameters
max_scale_factor_for_initial_images = 100;                   % Scale each VOC2012 image with a factor drawn uniformly at random from the range (0; max_scale_factor_synthetic_sinograms].
path_to_invivo_sinograms_for_std_distr_estimation = '???';   % Randomly scale all VOC2012 iamges so that the distribution of standard deviations of the generated sinograms matches with the distribution of standard deviations of the (invivo) sinograms in the given folder.
initial_img_transform = @(img) img.^2;                       % [Function handle or None] Data transformation that is applied to inital image after the scaling.

% Parameters for synthesizing a invivo test dataset
path_to_studies_folders_with_raw_data = '???';                                        % Path to raw data recorded by the MSOT scanner (for a Acuity MSOT scanner the folder that contains the 'Study_XX' folders).
path_to_csv = '???';                                                                  % Path to csv file that specifies for each MSOT scan that should be processed the related aquisitiions, a name idenitifier, and the manually tuned SoS.
data_name_prefix = 'deepmb_';                                                         % First part of the file name of the invivo sinograms and reconstructed images.
func_name_pulse_suffix = @(pulse_id) ['_' sprintf('%03d', 700+(pulse_id-1)*10) 'nm']; % Function that outputs for each aquisition the last part of the file name for the saved sinograms and reconstructed images.
broken_transducers = [];                                                              % e.g., [61, 149]. Indices list of broken transducers of the used MSOT system. The signals of these transducers are interpolated based on the acquired signals from neighboring transducers.
use_all_sos_instead_of_only_gt_sos_for_invivo_rec = false;                            % Specify if the in vivo sinograms should be reconstructed only with the manually tuned SoS or with all SoS from the defined range.
end
