class Parameters:

  def __init__(
    self,
    # Experiment
    EXPERIMENT_NAME,
    # Scanner ID
    SCANNER_ID,
    # Path and Data
    DATA_PATH,
    SAVE_PATH,
    DATASET_NAME_TRN_VAL,
    DATASET_NAME_TST,
    TARGET_IN_DATASET_TRN_VAL,
    TARGET_IN_DATASET_TST,
    ALTERNATIVE_TRAINING_ON_IN_VIVO_DATA,
    PARTICIPANT_ID_FOR_VAL,
    PARTICIPANT_ID_FOR_TST,
    # Speed of sound
    SOS_RANGE,
    SOS_ENCODING,
    SOS_NORMALIZATION_TO_INPUT_DATA_RANGE,
    # Batches
    BATCH_SIZE_TRN,
    BATCH_SIZE_VAL,
    BATCH_SIZE_TST,
    # Optimizer and Scheduler
    OPTIMIZER,
    NB_EPOCH,
    LEARNING_RATE,
    MOMENTUM,
    SCHEDULER_STEP_SIZE,
    SCHEDULER_GAMMA,
    # Signal-domain network
    SIG_NET_ARCHI,
    USE_BIAS_SIG,
    KERNEL_SIZE_UNET_SIG,
    PAD_SIZE_UNET_SIG,
    NB_LAYERS_UNET_SIG,
    NGF_UNET_SIG,
    PROVIDE_SOS_TO_NET_SIG,
    # Image-domain network
    IMA_NET_ARCHI,
    USE_BIAS_IMA,
    KERNEL_SIZE_UNET_IMA,
    PAD_SIZE_UNET_IMA,
    NB_LAYERS_UNET_IMA,
    NGF_UNET_IMA,
    CH_STEPS_DAMPING,
    KERNEL_SIZE_DAMPING,
    PAD_SIZE_DAMPING,
    PROVIDE_SOS_TO_NET_IMA,
    # Misc
    DIVISOR_FOR_INPUT_SINOGRAM_NORMALIZATION,
    DIVISOR_FOR_TARGET_IMAGE_NORMALIZATION,
    TRANSFORM_TRN_VAL_TARGETS,
    TRANSFORM_TST_NETWORK_OUTPUT,
    LOSS_NICKNAME,
    OUTPUT_ACTIVATION,
    RESUME_TRAINING,
    USE_PRETRAINING,
    SAMPLES_LIMIT,
    DETERMINISTIC,
    RANDOM_SEED,
    GPU_INDEX,
    # Selected images to print
    ID_PRINT_TRN,
    REGEX_PRINT_VAL,
    REGEX_PRINT_TST):

    # Experiment
    self.EXPERIMENT_NAME = EXPERIMENT_NAME

    # Scanner ID
    self.SCANNER_ID = SCANNER_ID

    # Path and Data
    self.DATA_PATH = DATA_PATH
    self.SAVE_PATH = SAVE_PATH
    self.DATASET_NAME_TRN_VAL = DATASET_NAME_TRN_VAL
    self.DATASET_NAME_TST = DATASET_NAME_TST
    self.TARGET_IN_DATASET_TRN_VAL = TARGET_IN_DATASET_TRN_VAL
    self.TARGET_IN_DATASET_TST = TARGET_IN_DATASET_TST
    self.ALTERNATIVE_TRAINING_ON_IN_VIVO_DATA = ALTERNATIVE_TRAINING_ON_IN_VIVO_DATA
    self.PARTICIPANT_ID_FOR_VAL = PARTICIPANT_ID_FOR_VAL
    self.PARTICIPANT_ID_FOR_TST = PARTICIPANT_ID_FOR_TST

    # Speed of sound
    self.SOS_RANGE = SOS_RANGE
    self.SOS_ENCODING = SOS_ENCODING
    self.SOS_NORMALIZATION_TO_INPUT_DATA_RANGE = SOS_NORMALIZATION_TO_INPUT_DATA_RANGE

    # Batches
    self.BATCH_SIZE_TRN = BATCH_SIZE_TRN
    self.BATCH_SIZE_VAL = BATCH_SIZE_VAL
    self.BATCH_SIZE_TST = BATCH_SIZE_TST

    # Optimizer and Scheduler
    self.OPTIMIZER = OPTIMIZER
    self.NB_EPOCH = NB_EPOCH
    self.LEARNING_RATE = LEARNING_RATE
    self.MOMENTUM = MOMENTUM
    self.SCHEDULER_STEP_SIZE = SCHEDULER_STEP_SIZE
    self.SCHEDULER_GAMMA = SCHEDULER_GAMMA

    # Signal-domain network
    self.SIG_NET_ARCHI = SIG_NET_ARCHI
    self.USE_BIAS_SIG = USE_BIAS_SIG
    self.KERNEL_SIZE_UNET_SIG = KERNEL_SIZE_UNET_SIG
    self.PAD_SIZE_UNET_SIG = PAD_SIZE_UNET_SIG
    self.NB_LAYERS_UNET_SIG = NB_LAYERS_UNET_SIG
    self.NGF_UNET_SIG = NGF_UNET_SIG
    self.PROVIDE_SOS_TO_NET_SIG = PROVIDE_SOS_TO_NET_SIG

    # Image-domain network
    self.IMA_NET_ARCHI = IMA_NET_ARCHI
    self.USE_BIAS_IMA = USE_BIAS_IMA
    self.KERNEL_SIZE_UNET_IMA = KERNEL_SIZE_UNET_IMA
    self.PAD_SIZE_UNET_IMA = PAD_SIZE_UNET_IMA
    self.NB_LAYERS_UNET_IMA = NB_LAYERS_UNET_IMA
    self.NGF_UNET_IMA = NGF_UNET_IMA
    self.CH_STEPS_DAMPING = CH_STEPS_DAMPING
    self.KERNEL_SIZE_DAMPING = KERNEL_SIZE_DAMPING
    self.PAD_SIZE_DAMPING = PAD_SIZE_DAMPING
    self.PROVIDE_SOS_TO_NET_IMA = PROVIDE_SOS_TO_NET_IMA

    # Misc
    self.DIVISOR_FOR_INPUT_SINOGRAM_NORMALIZATION = DIVISOR_FOR_INPUT_SINOGRAM_NORMALIZATION
    self.DIVISOR_FOR_TARGET_IMAGE_NORMALIZATION = DIVISOR_FOR_TARGET_IMAGE_NORMALIZATION
    self.TRANSFORM_TRN_VAL_TARGETS = TRANSFORM_TRN_VAL_TARGETS
    self.TRANSFORM_TST_NETWORK_OUTPUT = TRANSFORM_TST_NETWORK_OUTPUT
    self.LOSS_NICKNAME = LOSS_NICKNAME
    self.OUTPUT_ACTIVATION = OUTPUT_ACTIVATION
    self.RESUME_TRAINING = RESUME_TRAINING
    self.USE_PRETRAINING = USE_PRETRAINING
    self.SAMPLES_LIMIT = SAMPLES_LIMIT
    self.DETERMINISTIC = DETERMINISTIC
    self.RANDOM_SEED = RANDOM_SEED
    self.GPU_INDEX = GPU_INDEX

    # Selected images to print
    self.ID_PRINT_TRN = ID_PRINT_TRN
    self.REGEX_PRINT_VAL = REGEX_PRINT_VAL
    self.REGEX_PRINT_TST = REGEX_PRINT_TST
